// This file is auto-generated by @hey-api/openapi-ts

export const ClaimDtoSchema = {
  required: ['type', 'value'],
  type: 'object',
  properties: {
    type: {
      type: 'string',
      description: 'Claim type.',
    },
    value: {
      type: 'string',
      description: 'Claim value.',
    },
  },
  description: 'Represents a claim associated with a user.',
} as const;

export const ConfluenceDocSchema = {
  required: [
    'id',
    'type',
    'title',
    'body',
    'space',
    'versionNumber',
    'versionWhen',
    'versionBy',
    'createdDate',
    'createdBy',
    'ancestors',
    'labels',
  ],
  type: 'object',
  properties: {
    id: {
      type: 'string',
    },
    hash: {
      type: ['null', 'string'],
    },
    type: {
      type: ['null', 'string'],
    },
    title: {
      type: ['null', 'string'],
    },
    body: {
      type: ['null', 'string'],
    },
    space: {
      required: ['id', 'key', 'name', 'link'],
      type: 'object',
      properties: {
        id: {
          pattern: '^-?(?:0|[1-9]\\d*)$',
          type: ['integer', 'string'],
          format: 'int64',
        },
        key: {
          type: 'string',
        },
        name: {
          type: ['null', 'string'],
        },
        link: {
          type: ['null', 'string'],
        },
      },
    },
    versionNumber: {
      pattern: '^-?(?:0|[1-9]\\d*)$',
      type: ['integer', 'string'],
      format: 'int64',
    },
    versionWhen: {
      type: 'string',
      format: 'date-time',
    },
    versionBy: {
      required: ['username', 'userKey', 'displayName', 'profilePicturePath'],
      type: 'object',
      properties: {
        username: {
          type: ['null', 'string'],
        },
        userKey: {
          type: ['null', 'string'],
        },
        displayName: {
          type: ['null', 'string'],
        },
        profilePicturePath: {
          type: ['null', 'string'],
        },
      },
    },
    createdDate: {
      type: 'string',
      format: 'date-time',
    },
    createdBy: {
      required: ['username', 'userKey', 'displayName', 'profilePicturePath'],
      type: 'object',
      properties: {
        username: {
          type: ['null', 'string'],
        },
        userKey: {
          type: ['null', 'string'],
        },
        displayName: {
          type: ['null', 'string'],
        },
        profilePicturePath: {
          type: ['null', 'string'],
        },
      },
    },
    ancestors: {
      type: 'array',
      items: {
        required: ['id', 'type', 'title', 'link'],
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          type: {
            type: ['null', 'string'],
          },
          title: {
            type: ['null', 'string'],
          },
          link: {
            type: ['null', 'string'],
          },
        },
      },
    },
    labels: {
      type: 'array',
      items: {
        required: ['id', 'name', 'prefix'],
        type: 'object',
        properties: {
          id: {
            type: 'string',
          },
          name: {
            type: ['null', 'string'],
          },
          prefix: {
            type: ['null', 'string'],
          },
        },
      },
    },
    batchIndexDate: {
      type: 'string',
      format: 'date-time',
    },
  },
} as const;

export const DseHealthReportSchema = {
  required: ['status', 'totalDuration', 'checks'],
  type: 'object',
  properties: {
    status: {
      type: 'string',
      description: 'Overall status — `Healthy`, `Degraded`, or `Unhealthy`.',
    },
    totalDuration: {
      type: 'string',
      description: 'Wall-clock time taken to evaluate every check.',
    },
    checks: {
      type: 'array',
      items: {
        required: ['name', 'status', 'duration', 'description', 'exception', 'data'],
        type: 'object',
        properties: {
          name: {
            type: 'string',
            description: "The check's registration name (e.g. `elastic`, `self`).",
          },
          status: {
            type: 'string',
            description: "This check's status.",
          },
          duration: {
            type: 'string',
            description: 'How long this check took.',
          },
          description: {
            type: ['null', 'string'],
            description: 'Human-readable detail the check chose to report, if any.',
          },
          exception: {
            type: ['null', 'string'],
            description: 'The failure message when the check threw, if any.',
          },
          data: {
            type: 'object',
            description: 'Free-form diagnostic data the check attached.',
          },
        },
        description: 'The result of a single registered health check.',
      },
      description: 'One entry per registered health check.',
    },
  },
  description: 'Aggregated health of the service: overall status, total evaluation time, and a per-check breakdown.',
} as const;

export const ResponseSchema = {
  required: ['name', 'claims'],
  type: 'object',
  properties: {
    name: {
      type: ['null', 'string'],
      description: "Current user's name.",
    },
    claims: {
      type: 'array',
      items: {
        $ref: '#/components/schemas/ClaimDto',
      },
      description: "Current user's claims.",
    },
  },
  description: 'Returns information about the currently authenticated user.',
} as const;

export const UserInfoResponseSchema = {
  required: ['name', 'claims'],
  type: 'object',
  properties: {
    name: {
      type: ['null', 'string'],
      description: "Current user's name.",
    },
    claims: {
      type: 'array',
      items: {
        required: ['type', 'value'],
        type: 'object',
        properties: {
          type: {
            type: 'string',
            description: 'Claim type.',
          },
          value: {
            type: 'string',
            description: 'Claim value.',
          },
        },
        description: 'Represents a claim associated with a user.',
      },
      description: "Current user's claims.",
    },
  },
  description: 'Returns information about the currently authenticated user.',
} as const;
