// This file is auto-generated by @hey-api/openapi-ts

import type {Client, ClientMeta, Options as Options2, RequestResult, TDataShape} from './client';
import {client} from './client.gen';
import type {
  GetApiUserinfoData,
  GetApiUserinfoResponses,
  GetHealthData,
  GetHealthElasticData,
  GetHealthElasticErrors,
  GetHealthElasticResponses,
  GetHealthErrors,
  GetHealthLiveData,
  GetHealthLiveErrors,
  GetHealthLiveResponses,
  GetHealthReadyData,
  GetHealthReadyErrors,
  GetHealthReadyResponses,
  GetHealthResponses,
  GetHealthStartupData,
  GetHealthStartupErrors,
  GetHealthStartupResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Full health report
 *
 * Every registered check.
 */
export const getHealth = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthData, ThrowOnError>,
): RequestResult<GetHealthResponses, GetHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({url: '/health', ...options});

/**
 * Full health report
 *
 * Every registered check.
 */
export const getHealthStartup = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthStartupData, ThrowOnError>,
): RequestResult<GetHealthStartupResponses, GetHealthStartupErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthStartupResponses, GetHealthStartupErrors, ThrowOnError>({
    url: '/health/startup',
    ...options,
  });

/**
 * Liveness probe
 *
 * Process is up — no dependency checks run.
 */
export const getHealthLive = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthLiveData, ThrowOnError>,
): RequestResult<GetHealthLiveResponses, GetHealthLiveErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthLiveResponses, GetHealthLiveErrors, ThrowOnError>({
    url: '/health/live',
    ...options,
  });

/**
 * Readiness probe
 *
 * Process and its ready-tagged dependencies are reachable.
 */
export const getHealthReady = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthReadyData, ThrowOnError>,
): RequestResult<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError>({
    url: '/health/ready',
    ...options,
  });

/**
 * Health: elastic
 *
 * The 'elastic' check in isolation.
 */
export const getHealthElastic = <ThrowOnError extends boolean = true>(
  options?: Options<GetHealthElasticData, ThrowOnError>,
): RequestResult<GetHealthElasticResponses, GetHealthElasticErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetHealthElasticResponses, GetHealthElasticErrors, ThrowOnError>({
    url: '/health/elastic',
    ...options,
  });

export const getApiUserinfo = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiUserinfoData, ThrowOnError>,
): RequestResult<GetApiUserinfoResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiUserinfoResponses, unknown, ThrowOnError>({url: '/api/userinfo', ...options});
