// This file is auto-generated by @hey-api/openapi-ts

import type {Client, ClientMeta, Options as Options2, RequestResult, TDataShape} from './client';
import {client} from './client.gen';
import type {
  GetApiHealthData,
  GetApiHealthElasticData,
  GetApiHealthElasticErrors,
  GetApiHealthElasticResponses,
  GetApiHealthErrors,
  GetApiHealthLiveData,
  GetApiHealthLiveErrors,
  GetApiHealthLiveResponses,
  GetApiHealthReadyData,
  GetApiHealthReadyErrors,
  GetApiHealthReadyResponses,
  GetApiHealthResponses,
  GetApiHealthStartupData,
  GetApiHealthStartupErrors,
  GetApiHealthStartupResponses,
  GetApiUserinfoData,
  GetApiUserinfoResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Full health report
 *
 * Every registered check.
 */
export const getApiHealth = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiHealthData, ThrowOnError>,
): RequestResult<GetApiHealthResponses, GetApiHealthErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetApiHealthResponses, GetApiHealthErrors, ThrowOnError>({
    url: '/api/health',
    ...options,
  });

/**
 * Full health report
 *
 * Every registered check.
 */
export const getApiHealthStartup = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiHealthStartupData, ThrowOnError>,
): RequestResult<GetApiHealthStartupResponses, GetApiHealthStartupErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetApiHealthStartupResponses, GetApiHealthStartupErrors, ThrowOnError>({
    url: '/api/health/startup',
    ...options,
  });

/**
 * Liveness probe
 *
 * Process is up — no dependency checks run.
 */
export const getApiHealthLive = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiHealthLiveData, ThrowOnError>,
): RequestResult<GetApiHealthLiveResponses, GetApiHealthLiveErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetApiHealthLiveResponses, GetApiHealthLiveErrors, ThrowOnError>({
    url: '/api/health/live',
    ...options,
  });

/**
 * Readiness probe
 *
 * Process and its ready-tagged dependencies are reachable.
 */
export const getApiHealthReady = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiHealthReadyData, ThrowOnError>,
): RequestResult<GetApiHealthReadyResponses, GetApiHealthReadyErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetApiHealthReadyResponses, GetApiHealthReadyErrors, ThrowOnError>({
    url: '/api/health/ready',
    ...options,
  });

/**
 * Health: elastic
 *
 * The 'elastic' check in isolation.
 */
export const getApiHealthElastic = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiHealthElasticData, ThrowOnError>,
): RequestResult<GetApiHealthElasticResponses, GetApiHealthElasticErrors, ThrowOnError> =>
  (options?.client ?? client).get<GetApiHealthElasticResponses, GetApiHealthElasticErrors, ThrowOnError>({
    url: '/api/health/elastic',
    ...options,
  });

export const getApiUserinfo = <ThrowOnError extends boolean = true>(
  options?: Options<GetApiUserinfoData, ThrowOnError>,
): RequestResult<GetApiUserinfoResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetApiUserinfoResponses, unknown, ThrowOnError>({url: '/api/userinfo', ...options});
