// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type GetApiMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/me';
};

export type GetApiMeResponses = {
  /**
   * OK
   */
  200: unknown;
};
