// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zConfluenceDoc = z.object({
  id: z.string(),
  hash: z.string().nullish(),
  type: z.string().nullable(),
  title: z.string().nullable(),
  body: z.string().nullable(),
  space: z.object({
    id: z.union([
      z.coerce
        .bigint()
        .min(BigInt('-9223372036854775808'), {error: 'Invalid value: Expected int64 to be >= -9223372036854775808'})
        .max(BigInt('9223372036854775807'), {error: 'Invalid value: Expected int64 to be <= 9223372036854775807'}),
      z.coerce
        .bigint()
        .min(BigInt('-9223372036854775808'), {error: 'Invalid value: Expected int64 to be >= -9223372036854775808'})
        .max(BigInt('9223372036854775807'), {error: 'Invalid value: Expected int64 to be <= 9223372036854775807'}),
    ]),
    key: z.string(),
    name: z.string().nullable(),
    link: z.string().nullable(),
  }),
  versionNumber: z.union([
    z.coerce
      .bigint()
      .min(BigInt('-9223372036854775808'), {error: 'Invalid value: Expected int64 to be >= -9223372036854775808'})
      .max(BigInt('9223372036854775807'), {error: 'Invalid value: Expected int64 to be <= 9223372036854775807'}),
    z.coerce
      .bigint()
      .min(BigInt('-9223372036854775808'), {error: 'Invalid value: Expected int64 to be >= -9223372036854775808'})
      .max(BigInt('9223372036854775807'), {error: 'Invalid value: Expected int64 to be <= 9223372036854775807'}),
  ]),
  versionWhen: z.iso.datetime(),
  versionBy: z.object({
    username: z.string().nullable(),
    userKey: z.string().nullable(),
    displayName: z.string().nullable(),
    profilePicturePath: z.string().nullable(),
  }),
  createdDate: z.iso.datetime(),
  createdBy: z.object({
    username: z.string().nullable(),
    userKey: z.string().nullable(),
    displayName: z.string().nullable(),
    profilePicturePath: z.string().nullable(),
  }),
  ancestors: z.array(
    z.object({
      id: z.string(),
      type: z.string().nullable(),
      title: z.string().nullable(),
      link: z.string().nullable(),
    }),
  ),
  labels: z.array(
    z.object({
      id: z.string(),
      name: z.string().nullable(),
      prefix: z.string().nullable(),
    }),
  ),
  batchIndexDate: z.iso.datetime().optional(),
});
